# =============================================
#   SITE SETTINGS
# =============================================
title: "FM"
tagline: "(wannabe) Robotics Engineer"
description: ""
url: "https://chico1904.github.io"
baseurl: ""

author:
  name: "Francisco Miranda"
  github: "Chico1904"

# =============================================
#   THEME
# =============================================
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "aqua" #contrast, mint, neon, plum | air, aqua, contrast, dark, dirt, mint, neon, plum, sunrise

# =============================================
#   PLUGINS
# =============================================
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

# =============================================
#   DEFAULTS
# =============================================
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# =============================================
#   MARKDOWN & SYNTAX HIGHLIGHTING
# =============================================
markdown: kramdown
highlighter: rouge

# =============================================
#   EXCLUSIONS
# =============================================
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
  - vendor/
