# =============================================
#   SITE SETTINGS - run   bundle exec jekyll serve
# =============================================
title: "FM"
tagline: "(wannabe) Robotics Engineer"
description: "MSc Robotics @ KTH | 3D Vision & Scene Understanding"
url: "https://chico1904.github.io"
baseurl: ""

author:
  name: "Francisco Miranda"
  avatar: "/assets/images/me.jpeg"
  bio: "MSc Robotics @ KTH"
  location: "Stockholm, Sweden"
  links:
    - label: "franmira2003@gmail.com"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:franmira2003@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Chico1904"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ffmiranda/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/francisco_bfm"
    - label: "CV"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/CV.pdf"

# =============================================
#   THEME
# =============================================
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dirt" #  air, aqua, !contrast, dark, !dirt, mint, neon, plum, sunrise

# =============================================
#   PLUGINS
# =============================================
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

# =============================================
#   DEFAULTS
# =============================================
defaults:
  # Pages: About, Projects, Research
  - scope:
      path: ""
      type: pages
    values:
      layout: single   # normal page layout (no splash)
      classes: wide   # full-width content
      author_profile: true

# =============================================
#   MARKDOWN & SYNTAX HIGHLIGHTING
# =============================================
markdown: kramdown
highlighter: rouge

# =============================================
#   EXCLUSIONS
# =============================================
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
  - vendor/